<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-4MEIVF5" failures="1" tests="7" name="dsalgo_Testscenarios.Fail_Allure_TC" time="7.778" errors="0" timestamp="2023-03-04T21:53:26 EST" skipped="1">
  <testcase classname="dsalgo_Testscenarios.Fail_Allure_TC" name="opensign_inpage" time="0.790"/>
  <system-out/>
  <testcase classname="dsalgo_Testscenarios.Fail_Allure_TC" name="loginDDT" time="1.417"/>
  <system-out/>
  <testcase classname="dsalgo_Testscenarios.Fail_Allure_TC" name="loginDDT" time="1.448"/>
  <system-out/>
  <testcase classname="dsalgo_Testscenarios.Fail_Allure_TC" name="loginDDT" time="1.697"/>
  <system-out/>
  <testcase classname="dsalgo_Testscenarios.Fail_Allure_TC" name="logout" time="2.253">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:819)
at org.testng.Assert.assertEquals(Assert.java:829)
at dsalgo_Testscenarios.Fail_Allure_TC.logout(Fail_Allure_TC.java:78)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- logout -->
  <system-out/>
  <testcase classname="dsalgo_Testscenarios.Fail_Allure_TC" name="Skip_test" time="0.011">
    <skipped/>
  </testcase> <!-- Skip_test -->
  <system-out/>
  <testcase classname="dsalgo_Testscenarios.Fail_Allure_TC" name="back_to_home" time="0.162"/>
  <system-out/>
</testsuite> <!-- dsalgo_Testscenarios.Fail_Allure_TC -->
